import sys
sys.path.insert(0, 'python')
import zen
zen.loadLibrary('build/FastFLIP/libFLIPlib.so')

def substep():
        zen.substepBegin()
        if zen.G.substepid == 0: zen.addNode('RunOnce', 'No7')
        zen.applyNode('No7')
        if zen.G.substepid == 0: zen.addNode('ReadObjMesh', 'No28')
        zen.setNodeInput('No28', 'COND', 'No7::cond')
        zen.setNodeParam('No28', 'path', str(f'/home/dilei/Desktop/pig.obj'))
        zen.applyNode('No28')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No1084')
        zen.setNodeInput('No1084', 'port', 'No28::mesh')
        zen.setNodeParam('No1084', 'name', str(f'BoundaryMesh'))
        zen.applyNode('No1084')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1098')
        zen.setNodeParam('No1098', 'name', str(f'BoundaryMesh'))
        zen.applyNode('No1098')
        if zen.G.substepid == 0: zen.addNode('RunOnce', 'No74')
        zen.applyNode('No74')
        if zen.G.substepid == 0: zen.addNode('NumericFloat', 'No87')
        zen.setNodeInput('No87', 'COND', 'No74::cond')
        zen.setNodeParam('No87', 'value', float(0.03))
        zen.applyNode('No87')
        if zen.G.substepid == 0: zen.addNode('SetFrameTime', 'No80')
        zen.setNodeInput('No80', 'time', 'No87::value')
        zen.setNodeInput('No80', 'COND', 'No74::cond')
        zen.applyNode('No80')
        if zen.G.substepid == 0: zen.addNode('SetFLIPWorld', 'No52')
        zen.setNodeInput('No52', 'SRC', 'No80::DST')
        zen.setNodeInput('No52', 'COND', 'No74::cond')
        zen.setNodeParam('No52', 'dx', float(0.06))
        zen.applyNode('No52')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No95')
        zen.setNodeInput('No95', 'port', 'No52::Particles')
        zen.setNodeParam('No95', 'name', str(f'Particles'))
        zen.applyNode('No95')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No281')
        zen.setNodeParam('No281', 'name', str(f'Particles'))
        zen.applyNode('No281')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No123')
        zen.setNodeInput('No123', 'port', 'No52::Velocity')
        zen.setNodeParam('No123', 'name', str(f'Velocity'))
        zen.applyNode('No123')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1147')
        zen.setNodeParam('No1147', 'name', str(f'Velocity'))
        zen.applyNode('No1147')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No179')
        zen.setNodeParam('No179', 'name', str(f'Velocity'))
        zen.applyNode('No179')
        if zen.G.substepid == 0: zen.addNode('CFL_dt', 'No165')
        zen.setNodeInput('No165', 'Velocity', 'No179::port')
        zen.setNodeInput('No165', 'SRC', 'No52::DST')
        zen.setNodeParam('No165', 'dx', float(0.06))
        zen.applyNode('No165')
        if zen.G.substepid == 0: zen.addNode('PrintNumeric', 'No613')
        zen.setNodeInput('No613', 'value', 'No165::cfl_dt')
        zen.applyNode('No613')
        if zen.G.substepid == 0: zen.addNode('IntegrateFrameTime', 'No186')
        zen.setNodeInput('No186', 'desired_dt', 'No165::cfl_dt')
        zen.setNodeInput('No186', 'SRC', 'No613::DST')
        zen.applyNode('No186')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No206')
        zen.setNodeInput('No206', 'port', 'No186::actual_dt')
        zen.setNodeParam('No206', 'name', str(f'step_dt'))
        zen.applyNode('No206')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1105')
        zen.setNodeParam('No1105', 'name', str(f'step_dt'))
        zen.applyNode('No1105')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No151')
        zen.setNodeInput('No151', 'port', 'No52::LiquidSDF')
        zen.setNodeParam('No151', 'name', str(f'LiquidSDF'))
        zen.applyNode('No151')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1111')
        zen.setNodeParam('No1111', 'name', str(f'LiquidSDF'))
        zen.applyNode('No1111')
        if zen.G.substepid == 0: zen.addNode('MeshToSDF', 'No35')
        zen.setNodeInput('No35', 'mesh', 'No28::mesh')
        zen.setNodeInput('No35', 'COND', 'No7::cond')
        zen.setNodeParam('No35', 'voxel_size', float(0.06))
        zen.applyNode('No35')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No43')
        zen.setNodeInput('No43', 'port', 'No35::sdf')
        zen.setNodeParam('No43', 'name', str(f'Boundary'))
        zen.applyNode('No43')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1117')
        zen.setNodeParam('No1117', 'name', str(f'Boundary'))
        zen.applyNode('No1117')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No157')
        zen.setNodeInput('No157', 'port', 'No52::ExtractedLiquidSDF')
        zen.setNodeParam('No157', 'name', str(f'ExtractedLiquidSDF'))
        zen.applyNode('No157')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1129')
        zen.setNodeParam('No1129', 'name', str(f'ExtractedLiquidSDF'))
        zen.applyNode('No1129')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No102')
        zen.setNodeInput('No102', 'port', 'No52::Pressure')
        zen.setNodeParam('No102', 'name', str(f'Pressure'))
        zen.applyNode('No102')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1135')
        zen.setNodeParam('No1135', 'name', str(f'Pressure'))
        zen.applyNode('No1135')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No116')
        zen.setNodeInput('No116', 'port', 'No52::CellFWeight')
        zen.setNodeParam('No116', 'name', str(f'CellFWeight'))
        zen.applyNode('No116')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1141')
        zen.setNodeParam('No1141', 'name', str(f'CellFWeight'))
        zen.applyNode('No1141')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No135')
        zen.setNodeInput('No135', 'port', 'No52::SolidVelocity')
        zen.setNodeParam('No135', 'name', str(f'SolidVelocity'))
        zen.applyNode('No135')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1153')
        zen.setNodeParam('No1153', 'name', str(f'SolidVelocity'))
        zen.applyNode('No1153')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No109')
        zen.setNodeInput('No109', 'port', 'No52::Divergence')
        zen.setNodeParam('No109', 'name', str(f'Divergence'))
        zen.applyNode('No109')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No1123')
        zen.setNodeParam('No1123', 'name', str(f'Divergence'))
        zen.applyNode('No1123')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No445')
        zen.setNodeParam('No445', 'name', str(f'step_dt'))
        zen.applyNode('No445')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No452')
        zen.setNodeParam('No452', 'name', str(f'Velocity'))
        zen.applyNode('No452')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No459')
        zen.setNodeParam('No459', 'name', str(f'CellFWeight'))
        zen.applyNode('No459')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No413')
        zen.setNodeParam('No413', 'name', str(f'LiquidSDF'))
        zen.applyNode('No413')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No420')
        zen.setNodeParam('No420', 'name', str(f'Boundary'))
        zen.applyNode('No420')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No427')
        zen.setNodeParam('No427', 'name', str(f'ExtractedLiquidSDF'))
        zen.applyNode('No427')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No383')
        zen.setNodeParam('No383', 'name', str(f'LiquidSDF'))
        zen.applyNode('No383')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No390')
        zen.setNodeParam('No390', 'name', str(f'Boundary'))
        zen.applyNode('No390')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No397')
        zen.setNodeParam('No397', 'name', str(f'CellFWeight'))
        zen.applyNode('No397')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No368')
        zen.setNodeParam('No368', 'name', str(f'Velocity'))
        zen.applyNode('No368')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No361')
        zen.setNodeParam('No361', 'name', str(f'Particles'))
        zen.applyNode('No361')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No325')
        zen.setNodeParam('No325', 'name', str(f'Velocity'))
        zen.applyNode('No325')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No129')
        zen.setNodeInput('No129', 'port', 'No52::PostAdvVelocity')
        zen.setNodeParam('No129', 'name', str(f'PostAdvVelocity'))
        zen.applyNode('No129')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No305')
        zen.setNodeParam('No305', 'name', str(f'PostAdvVelocity'))
        zen.applyNode('No305')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No141')
        zen.setNodeInput('No141', 'port', 'No52::VelocityWeights')
        zen.setNodeParam('No141', 'name', str(f'VelocityWeights'))
        zen.applyNode('No141')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No333')
        zen.setNodeParam('No333', 'name', str(f'VelocityWeights'))
        zen.applyNode('No333')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No340')
        zen.setNodeParam('No340', 'name', str(f'LiquidSDF'))
        zen.applyNode('No340')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No347')
        zen.setNodeParam('No347', 'name', str(f'ExtractedLiquidSDF'))
        zen.applyNode('No347')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No253')
        zen.setNodeParam('No253', 'name', str(f'Particles'))
        zen.applyNode('No253')
        if zen.G.substepid == 0: zen.addNode('ReadObjMesh', 'No1')
        zen.setNodeInput('No1', 'COND', 'No7::cond')
        zen.setNodeParam('No1', 'path', str(f'/home/dilei/Desktop/Pig_Head.obj'))
        zen.applyNode('No1')
        if zen.G.substepid == 0: zen.addNode('MeshToSDF', 'No13')
        zen.setNodeInput('No13', 'mesh', 'No1::mesh')
        zen.setNodeInput('No13', 'COND', 'No7::cond')
        zen.setNodeParam('No13', 'voxel_size', float(0.06))
        zen.applyNode('No13')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No21')
        zen.setNodeInput('No21', 'port', 'No13::sdf')
        zen.setNodeParam('No21', 'name', str(f'Emitter'))
        zen.applyNode('No21')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No260')
        zen.setNodeParam('No260', 'name', str(f'Emitter'))
        zen.applyNode('No260')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No267')
        zen.setNodeParam('No267', 'name', str(f'LiquidSDF'))
        zen.applyNode('No267')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No213')
        zen.setNodeParam('No213', 'name', str(f'step_dt'))
        zen.applyNode('No213')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No220')
        zen.setNodeParam('No220', 'name', str(f'Particles'))
        zen.applyNode('No220')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No227')
        zen.setNodeParam('No227', 'name', str(f'Velocity'))
        zen.applyNode('No227')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No234')
        zen.setNodeParam('No234', 'name', str(f'PostAdvVelocity'))
        zen.applyNode('No234')
        if zen.G.substepid == 0: zen.addNode('G2P_Advector', 'No194')
        zen.setNodeInput('No194', 'dt', 'No213::port')
        zen.setNodeInput('No194', 'Particles', 'No220::port')
        zen.setNodeInput('No194', 'Velocity', 'No227::port')
        zen.setNodeInput('No194', 'PostAdvVelocity', 'No234::port')
        zen.setNodeInput('No194', 'SRC', 'No186::DST')
        zen.setNodeParam('No194', 'dx', float(0.06))
        zen.setNodeParam('No194', 'RK_ORDER', int(1))
        zen.setNodeParam('No194', 'pic_smoothness', float(0.02))
        zen.applyNode('No194')
        if zen.G.substepid == 0: zen.addNode('ParticleEmitter', 'No241')
        zen.setNodeInput('No241', 'Particles', 'No253::port')
        zen.setNodeInput('No241', 'ShapeSDF', 'No260::port')
        zen.setNodeInput('No241', 'LiquidSDF', 'No267::port')
        zen.setNodeInput('No241', 'SRC', 'No194::DST')
        zen.setNodeParam('No241', 'vx', float(0))
        zen.setNodeParam('No241', 'vy', float(0))
        zen.setNodeParam('No241', 'vz', float(0))
        zen.applyNode('No241')
        if zen.G.substepid == 0: zen.addNode('FLIP_P2G', 'No312')
        zen.setNodeInput('No312', 'Particles', 'No361::port')
        zen.setNodeInput('No312', 'Velocity', 'No325::port')
        zen.setNodeInput('No312', 'PostP2GVelocity', 'No305::port')
        zen.setNodeInput('No312', 'VelocityWeights', 'No333::port')
        zen.setNodeInput('No312', 'LiquidSDF', 'No340::port')
        zen.setNodeInput('No312', 'ExtractedLiquidSDF', 'No347::port')
        zen.setNodeInput('No312', 'SRC', 'No241::DST')
        zen.setNodeParam('No312', 'dx', float(0.06))
        zen.applyNode('No312')
        if zen.G.substepid == 0: zen.addNode('Vec3FieldExtrapolate', 'No354')
        zen.setNodeInput('No354', 'Field', 'No368::port')
        zen.setNodeInput('No354', 'SRC', 'No312::DST')
        zen.setNodeParam('No354', 'NumIterates', int(2))
        zen.applyNode('No354')
        if zen.G.substepid == 0: zen.addNode('CutCellWeight', 'No375')
        zen.setNodeInput('No375', 'LiquidSDF', 'No383::port')
        zen.setNodeInput('No375', 'SolidSDF', 'No390::port')
        zen.setNodeInput('No375', 'FaceWeight', 'No397::port')
        zen.setNodeInput('No375', 'SRC', 'No354::DST')
        zen.applyNode('No375')
        if zen.G.substepid == 0: zen.addNode('PushOutLiquidSDF', 'No404')
        zen.setNodeInput('No404', 'LiquidSDF', 'No413::port')
        zen.setNodeInput('No404', 'SolidSDF', 'No420::port')
        zen.setNodeInput('No404', 'ExtractedLiquidSDF', 'No427::port')
        zen.setNodeInput('No404', 'SRC', 'No375::DST')
        zen.setNodeParam('No404', 'dx', float(0.06))
        zen.applyNode('No404')
        if zen.G.substepid == 0: zen.addNode('FieldAddVector', 'No434')
        zen.setNodeInput('No434', 'dt', 'No445::port')
        zen.setNodeInput('No434', 'Velocity', 'No452::port')
        zen.setNodeInput('No434', 'FieldWeight', 'No459::port')
        zen.setNodeInput('No434', 'SRC', 'No404::DST')
        zen.setNodeParam('No434', 'vx', float(0))
        zen.setNodeParam('No434', 'vy', float(-9.8))
        zen.setNodeParam('No434', 'vz', float(0))
        zen.applyNode('No434')
        if zen.G.substepid == 0: zen.addNode('AssembleSolvePPE', 'No466')
        zen.setNodeInput('No466', 'dt', 'No1105::port')
        zen.setNodeInput('No466', 'LiquidSDF', 'No1111::port')
        zen.setNodeInput('No466', 'ExtractedLiquidSDF', 'No1129::port')
        zen.setNodeInput('No466', 'Divergence', 'No1123::port')
        zen.setNodeInput('No466', 'Pressure', 'No1135::port')
        zen.setNodeInput('No466', 'CellFWeight', 'No1141::port')
        zen.setNodeInput('No466', 'Velocity', 'No1147::port')
        zen.setNodeInput('No466', 'SolidVelocity', 'No1153::port')
        zen.setNodeInput('No466', 'SRC', 'No434::DST')
        zen.setNodeParam('No466', 'dx', float(0.06))
        zen.applyNode('No466')
        if zen.G.substepid == 0: zen.addNode('SubtractPressureGradient', 'No1062')
        zen.setNodeInput('No1062', 'dt', 'No1105::port')
        zen.setNodeInput('No1062', 'LiquidSDF', 'No1111::port')
        zen.setNodeInput('No1062', 'SolidSDF', 'No1117::port')
        zen.setNodeInput('No1062', 'ExtractedLiquidSDF', 'No1129::port')
        zen.setNodeInput('No1062', 'Pressure', 'No1135::port')
        zen.setNodeInput('No1062', 'CellFWeight', 'No1141::port')
        zen.setNodeInput('No1062', 'Velocity', 'No1147::port')
        zen.setNodeInput('No1062', 'SolidVelocity', 'No1153::port')
        zen.setNodeInput('No1062', 'SRC', 'No466::DST')
        zen.setNodeParam('No1062', 'dx', float(0.06))
        zen.applyNode('No1062')
        if zen.G.substepid == 0: zen.addNode('Vec3FieldExtrapolate', 'No1076')
        zen.setNodeInput('No1076', 'Field', 'No1147::port')
        zen.setNodeInput('No1076', 'SRC', 'No1062::DST')
        zen.setNodeParam('No1076', 'NumIterates', int(5))
        zen.applyNode('No1076')
        if zen.G.substepid == 0: zen.addNode('GetVDBPoints', 'No274')
        zen.setNodeInput('No274', 'grid', 'No281::port')
        zen.setNodeInput('No274', 'SRC', 'No1076::DST')
        zen.applyNode('No274')
        if zen.G.substepid == 0: zen.addNode('RunAfterFrame', 'No294')
        zen.applyNode('No294')
        if zen.G.substepid == 0: zen.addNode('ViewParticles', 'No288')
        zen.setNodeInput('No288', 'pars', 'No274::pars')
        zen.setNodeInput('No288', 'COND', 'No294::cond')
        zen.applyNode('No288')
        if zen.G.substepid == 0: zen.addNode('ViewMesh', 'No1091')
        zen.setNodeInput('No1091', 'mesh', 'No1098::port')
        zen.setNodeInput('No1091', 'SRC', 'No288::DST')
        zen.setNodeInput('No1091', 'COND', 'No294::cond')
        zen.applyNode('No1091')
        if zen.G.substepid == 0: zen.addNode('PortalIn', 'No593')
        zen.setNodeInput('No593', 'port', 'No1091::DST')
        zen.setNodeParam('No593', 'name', str(f'finalSelect'))
        zen.applyNode('No593')
        if zen.G.substepid == 0: zen.addNode('PortalOut', 'No600')
        zen.setNodeParam('No600', 'name', str(f'finalSelect'))
        zen.applyNode('No600')
        if zen.G.substepid == 0: zen.addNode('Route', 'No606')
        zen.setNodeInput('No606', 'input', 'No600::port')
        zen.applyNode('No606')
        zen.substepEnd()

def execute():
        zen.frameBegin()
        while zen.substepShouldContinue():
                substep()
        zen.frameEnd()

for frame in range(20):
        print('[Zen] executing frame', frame)
        execute()
