cmake -B Debug ^
-DCMAKE_BUILD_TYPE=Debug ^
-DCMAKE_PREFIX_PATH=C:/Qt/lib/cmake ^
-DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" ^
-DREFLECTION_USE_PREBUILT_BINARY=OFF ^
-DREFLECT_BUILD_EXAMPLE=OFF ^
-DZENO_WIN32_RC=ON ^
