# vim: ft=dockerfile

FROM ubuntu:20.04

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt clean
RUN apt-get update -y
RUN apt-get install -y git
RUN apt-get install -y gcc
RUN apt-get install -y make
RUN apt-get install -y cmake
RUN apt-get install -y python-is-python3
RUN apt-get install -y python-dev-is-python3
RUN apt-get install -y python3-pip
RUN apt-get install -y libqt5core5a
RUN apt-get install -y qt5dxcb-plugin
RUN apt-get install -y libglvnd-dev
RUN apt-get install -y libglapi-mesa
RUN apt-get install -y libosmesa6

RUN python -m pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
RUN python -m pip install -U pip
RUN python -m pip install pybind11
RUN python -m pip install numpy
RUN python -m pip install PyQt5

RUN echo git clone https://gitee.com/archibate/zeno.git --depth=1 > /root/get-zeno.sh && chmod +x /root/get-zeno.sh

ENTRYPOINT bash
