#!/usr/bin/env python3

import subprocess

args = [
'-DCMAKE_BUILD_TYPE=RelWithDebInfo',
'-DZENOFX_ENABLE_OPENVDB:BOOL=ON',
'-DEXTENSION_oldzenbase:BOOL=ON',
'-DEXTENSION_ZenoFX:BOOL=ON',
'-DEXTENSION_Rigid:BOOL=ON',
'-DEXTENSION_FastFLIP:BOOL=ON',
'-DEXTENSION_zenvdb:BOOL=ON',
'-DZENO_ENABLE_PYTHON:BOOL=ON',
'-DZENO_ENABLE_OPENMP:BOOL=ON',
'-DZENO_FAULTHANDLER:BOOL=ON',
'-DZENO_GLOBALSTATE:BOOL=ON',
'-DZENO_VISUALIZATION:BOOL=ON',
'-DZENO_BENCHMARKING:BOOL=ON',
'-DZENO_BUILD_EXTENSIONS:BOOL=ON',
'-DZENO_FAIL_SILENTLY:BOOL=OFF',
'-DZENO_BUILD_TESTS:BOOL=OFF',
'-DZENO_BUILD_ZFX:BOOL=ON',
]

subprocess.check_call(['cmake', '-B', 'build'] + args)
