#ifndef __MODEL_ROLE_H__
#define __MODEL_ROLE_H__

enum MODEL_ROLE
{
	ROLE_OBJID = Qt::UserRole + 1,	// like "0xgrwe-MakeCurveMap", which is a ident.
	ROLE_OBJNAME,	// like "MakeCurveMap", which is a node "class" name.
	ROLE_NODETYPE,
	ROLE_OBJPOS,
	ROLE_OBJRECT,
	ROLE_SRCNODE,
	ROLE_DSTNODE,
	ROLE_PARAMETERS,
	ROLE_PARAMETERS_NOT_DESC,	//params supply for node but invisible, like _POINTS, _HANDLERS
	ROLE_INPUTS,
	ROLE_OUTPUTS,
	ROLE_OPTIONS,
	ROLE_SOCKET_KEYS,
	ROLE_COLLASPED,
	ROLE_COLORRAMPS,
	ROLE_GRAPHPTR,
	ROLE_BLACKBOARD,

	//synchronize link change, param
	ROLE_ADDLINK,
	ROLE_REMOVELINK,
	ROLE_MODIFY_PARAM,
	ROLE_MODIFY_SOCKET,
	ROLE_MODIFY_SOCKET_DEFL,

	//link role
	ROLE_OUTNODE,
	ROLE_INNODE,
	ROLE_OUTSOCK,
	ROLE_INSOCK,
};

enum LOG_ROLE
{
    ROLE_LOGTYPE = Qt::UserRole + 1,
	ROLE_TIME,
	ROLE_FILENAME,
	ROLE_LINENO,
	ROLE_NODE_IDENT,
};

#endif
