#include <cuda.h>
#include <nvrtc.h>
#include <cuda_runtime.h>
#include <iostream>
#include <string>
#include <vector>
#include <cstdio>

#define CU(x) do { \
    CUresult __res = (x); \
    if (__res != CUDA_SUCCESS) { \
        const char *__err; \
        cuGetErrorString(__res, &__err); \
        printf("%s:%d: %s: %s\n", __FILE__, __LINE__, #x, __err); \
        abort(); \
    } \
} while (0)

#define NVRTC(x) do { \
    nvrtcResult __res = (x); \
    if (__res != NVRTC_SUCCESS) { \
        const char *__err = nvrtcGetErrorString(__res); \
        printf("%s:%d: %s: %s\n", __FILE__, __LINE__, #x, __err); \
        abort(); \
    } \
} while (0)


static std::string ptx = R"(
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-29920130
// Cuda compilation tools, release 11.3, V11.3.109
// Based on NVVM 7.0.1
//

.version 7.3
.target sm_75
.address_size 64

	// .globl	_Z6kernelv
.extern .func  (.param .b32 func_retval0) vprintf
(
	.param .b64 vprintf_param_0,
	.param .b64 vprintf_param_1
)
;
.global .align 1 .b8 $str[15] = {70, 85, 67, 75, 32, 85, 32, 78, 86, 73, 68, 73, 65, 10, 0};

.visible .entry _Z6kernelv()
{
	.reg .b32 	%r<2>;
	.reg .b64 	%rd<4>;


	mov.u64 	%rd1, $str;
	cvta.global.u64 	%rd2, %rd1;
	mov.u64 	%rd3, 0;
	{ // callseq 0, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd2;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd3;
	.param .b32 retval0;
	call.uni (retval0),
	vprintf,
	(
	param0,
	param1
	);
	ld.param.b32 	%r1, [retval0+0];
	} // callseq 0
	ret;

}
    )";


int main() {
    CU(cuInit(0));

    CUdevice dev;
    CU(cuDeviceGet(&dev, 0));

    int major, minor;
    CU(cuDeviceGetAttribute(&major,
        CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, dev));
    CU(cuDeviceGetAttribute(&minor,
        CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, dev));

    printf("SM %d%d\n", major, minor);

    CUcontext ctx;
    CU(cuCtxCreate(&ctx, 0, dev));

    const char *source = R"(
    __global__ void callee() {
        printf("IM THE ONE BE FUCKED!\n");
    }
    )";

    char compileParam0[256];
    sprintf(compileParam0, "--gpu-architecture=sm_%d%d", major, minor);
    char *compileParams[] = {compileParam0};

    nvrtcProgram prog;
    nvrtcCreateProgram(&prog, source, "<nvrtc>", 0, NULL, NULL);
    nvrtcResult res = nvrtcCompileProgram(prog, 1, compileParams);

    size_t codeSize;
    NVRTC(nvrtcGetPTXSize(prog, &codeSize));
    char *code = new char[codeSize];
    NVRTC(nvrtcGetPTX(prog, code));

    size_t logSize;
    NVRTC(nvrtcGetProgramLogSize(prog, &logSize));
    char *log = (char *)malloc(logSize + 1);
    NVRTC(nvrtcGetProgramLog(prog, log));
    log[logSize] = '\0';
    if (strlen(log) >= 2) {
        std::cerr << "\n compilation log ---\n";
        std::cerr << log;
        std::cerr << "\n end log ---\n";
    }

    CUlinkState state;
    CU(cuLinkCreate(0, NULL, NULL, &state));

    CU(cuLinkAddData(state, CU_JIT_INPUT_PTX, ptx.data(),
        ptx.size(), "kernel", 0, NULL, NULL));

    CU(cuLinkAddData(state, CU_JIT_INPUT_PTX, code,
        codeSize, "nvrtc", 0, NULL, NULL));

    void *cubin;
    size_t cubinSize;
    CU(cuLinkComplete(state, &cubin, &cubinSize));

    CUmodule module;
    CU(cuModuleLoadData(&module, cubin));

    CUfunction function;
    cuModuleGetFunction(&function, module, "_Z6kernelv");

    CU(cuLaunchKernel(function,
            1, 1, 1, 1, 1, 1,
            0, 0, NULL, 0));

    CU(cuCtxSynchronize());

    printf("done\n");

    return 0;
}
