#ifndef __MODEL_ROLE_H__
#define __MODEL_ROLE_H__

enum MODEL_ROLE
{
	ROLE_OBJID = Qt::UserRole + 1,
	ROLE_OBJNAME,
	ROLE_NODETYPE,
	ROLE_OBJPOS,
	ROLE_OBJRECT,
	ROLE_SRCNODE,
	ROLE_DSTNODE,
	ROLE_PARAMETERS,
	ROLE_INPUTS,
	ROLE_OUTPUTS,
	ROLE_OPTIONS,
	ROLE_SOCKET_KEYS,
	ROLE_COLLASPED,
	ROLE_COLORRAMPS,
	ROLE_GRAPHPTR,
	ROLE_BLACKBOARD,

	//synchronize link change, param
	ROLE_ADDLINK,
	ROLE_REMOVELINK,
	ROLE_MODIFY_PARAM,
};

#endif
