#!/bin/bash
set -e

# https://github.com/mkropat/sh-realpath/blob/master/realpath.sh {{{

myrealpath() {
    canonicalize_path "$(resolve_symlinks "$1")"
}

resolve_symlinks() {
    _resolve_symlinks "$1"
}

_resolve_symlinks() {
    _assert_no_path_cycles "$@" || return

    local dir_context path
    path=$(readlink -- "$1")
    if [ $? -eq 0 ]; then
        dir_context=$(dirname -- "$1")
        _resolve_symlinks "$(_prepend_dir_context_if_necessary "$dir_context" "$path")" "$@"
    else
        printf '%s\n' "$1"
    fi
}

_prepend_dir_context_if_necessary() {
    if [ "$1" = . ]; then
        printf '%s\n' "$2"
    else
        _prepend_path_if_relative "$1" "$2"
    fi
}

_prepend_path_if_relative() {
    case "$2" in
        /* ) printf '%s\n' "$2" ;;
         * ) printf '%s\n' "$1/$2" ;;
    esac
}

_assert_no_path_cycles() {
    local target path

    target=$1
    shift

    for path in "$@"; do
        if [ "$path" = "$target" ]; then
            return 1
        fi
    done
}

canonicalize_path() {
    if [ -d "$1" ]; then
        _canonicalize_dir_path "$1"
    else
        _canonicalize_file_path "$1"
    fi
}

_canonicalize_dir_path() {
    (cd "$1" 2>/dev/null && pwd -P)
}

_canonicalize_file_path() {
    local dir file
    dir=$(dirname -- "$1")
    file=$(basename -- "$1")
    (cd "$dir" 2>/dev/null && printf '%s/%s\n' "$(pwd -P)" "$file")
}

# Optionally, you may also want to include:

### readlink emulation ###

readlink() {
    if _has_command readlink; then
        _system_readlink "$@"
    else
        _emulated_readlink "$@"
    fi
}

_has_command() {
    hash -- "$1" 2>/dev/null
}

_system_readlink() {
    command readlink "$@"
}

_emulated_readlink() {
    if [ "$1" = -- ]; then
        shift
    fi

    _gnu_stat_readlink "$@" || _bsd_stat_readlink "$@"
}

_gnu_stat_readlink() {
    local output
    output=$(stat -c %N -- "$1" 2>/dev/null) &&

    printf '%s\n' "$output" |
        sed "s/^‘[^’]*’ -> ‘\(.*\)’/\1/
             s/^'[^']*' -> '\(.*\)'/\1/"
    # FIXME: handle newlines
}

_bsd_stat_readlink() {
    stat -f %Y -- "$1" 2>/dev/null
}
################################################# }}}

real="$(myrealpath "$0")"
root="$(dirname -- "$real")"
base="$(basename -- "$0")"

if [ "x" == "x$LIBGL_DRIVERS_PATH" ]; then
    for x in /usr/lib/dri /usr/lib/x86_64-linux-gnu/dri; do
        if [ -d $x ]; then
            export LIBGL_DRIVERS_PATH="$x"
            break
        fi
    done
fi

if [ "x" == "x$PYTHONHOME" ]; then
    export PYTHONHOME="$root"
fi

#if [ "x" != "x$ldmock_no_ldlinux" ]; then
    #export ldmock_no_ldlinux=1
    #export LD_LIBRARY_PATH="$root/lib:$LD_LIBRARY_PATH"
    #exec -a "$0" -- "$root/.bin/$base" "$@"
#fi

exec "$root/lib/ld-linux-x86-64.so.2" --library-path "$root/lib" --argv0 "$0" "$root/.bin/$base" "$@"
