#ifdef _ZENO_CGMESH_USE_IGL_UNUSED_MOCK
extern "C" void _ZN3igl9hausdorffIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEEdEEvRKNS1_10MatrixBaseIT_EERKSt8functionIFT0_RKSA_SC_SC_EERSA_SH_();
namespace zeno::___nvm_unused_details___ {
    void _unused() { _ZN3igl9hausdorffIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEEdEEvRKNS1_10MatrixBaseIT_EERKSt8functionIFT0_RKSA_SC_SC_EERSA_SH_(); }
}
#endif
