include(cmake/ZPM.cmake)

#zpm_requires(3rdparty/pkgs/fmt -DFMT_DOC:BOOL=OFF -DFMT_TEST:BOOL=OFF)
#zpm_requires(3rdparty/pkgs/spdlog -DSPDLOG_FMT_EXTERNAL:BOOL=ON -DSPDLOG_BUILD_EXAMPLE:BOOL=OFF)
#zpm_requires(3rdparty/pkgs/range-v3 -DRANGE_V3_DOCS:BOOL=OFF -DRANGE_V3_TESTS:BOOL=OFF -DRANGE_V3_EXAMPLES:BOOL=OFF)
#zpm_requires(3rdparty/pkgs/python-cmake-buildsystem)
#zpm_requires(3rdparty/pkgs/BoostBuilder)
#zpm_requires(3rdparty/pkgs/eigen)
#zpm_requires(3rdparty/pkgs/zlib)
#zpm_requires(3rdparty/pkgs/c-blosc -DBUILD_TESTS:BOOL=OFF)
zpm_requires(3rdparty/pkgs/tbb -DTBB_BUILD_TESTS:BOOL=OFF -DTBB_BUILD_STATIC:BOOL=ON -DTBB_BUILD_SHARED:BOOL=OFF)
#zpm_requires(3rdparty/pkgs/openvdb)
zpm_finalize()
