include(cmake/ZPM.cmake)

#zpm_requires(3rdparty/pkgs/BoostBuilder)
#zpm_requires(3rdparty/pkgs/zlib)
#zpm_requires(3rdparty/pkgs/c-blosc -DBUILD_TESTS:BOOL=OFF)
zpm_requires(3rdparty/pkgs/tbb -DTBB_BUILD_TESTS:BOOL=OFF)
#zpm_requires(3rdparty/pkgs/openvdb)
#zpm_requires(3rdparty/pkgs/eigen)
zpm_requires(3rdparty/pkgs/fmt -DFMT_DOC:BOOL=OFF -DFMT_TEST:BOOL=OFF)
zpm_requires(3rdparty/pkgs/spdlog -DSPDLOG_FMT_EXTERNAL:BOOL=ON -DSPDLOG_BUILD_EXAMPLE:BOOL=OFF)
zpm_finalize()
