#ifndef __ZENO_COMMON_H__
#define __ZENO_COMMON_H__

#include <variant>
#include <string>
#include <vector>
#include <list>
#include <functional>
#include <zeno/utils/vec.h>


#define ENUM_FLAGS(enum_class) \
constexpr enum_class operator|(enum_class X, enum_class Y) {\
    return static_cast<enum_class>(\
        static_cast<unsigned int>(X) | static_cast<unsigned int>(Y));\
}\
\
constexpr enum_class operator&(enum_class X, enum_class Y) {\
    return static_cast<enum_class>(\
        static_cast<unsigned int>(X) & static_cast<unsigned int>(Y));\
}\
\
constexpr enum_class operator^(enum_class X, enum_class Y) {\
    return static_cast<enum_class>(\
        static_cast<unsigned int>(X) ^ static_cast<unsigned int>(Y));\
}\

namespace zeno {

    using ParamType = size_t;
    //enum ParamType
    //{
    #define Param_Bool zeno::types::gParamType_Bool
    #define Param_Int zeno::types::gParamType_Int
    #define Param_String zeno::types::gParamType_String
    #define Param_Float zeno::types::gParamType_Float
    #define Param_Vec2i zeno::types::gParamType_Vec2i
    #define Param_Vec3i zeno::types::gParamType_Vec3i
    #define Param_Vec4i zeno::types::gParamType_Vec4i
    #define Param_Vec2f zeno::types::gParamType_Vec2f
    #define Param_Vec3f zeno::types::gParamType_Vec3f
    #define Param_Vec4f zeno::types::gParamType_Vec4f
    #define Param_Prim  zeno::types::gParamType_Primitive
    #define Param_Camera zeno::types::gParamType_Camera
    #define Param_Light zeno::types::gParamType_Light
    #define Param_Material zeno::types::gParamType_sharedIObject
    #define Param_VdbGrid zeno::types::gParamType_sharedIObject
    #define Param_Dict zeno::types::gParamType_Dict
    #define Param_List zeno::types::gParamType_List
    #define Param_Curve zeno::types::gParamType_Curve
    #define Param_Heatmap zeno::types::gParamType_Heatmap
    #define Param_Null 0
    #define Param_SrcDst 1
    #define Param_Object 2
    #define Param_Custom 3
    //};

    enum NodeStatus : unsigned int
    {
        None = 0,
        Mute = 1,
        View = 1<<1,
    };
    ENUM_FLAGS(NodeStatus)

    enum NodeType
    {
        Node_Normal,
        SubInput,
        SubOutput,
        Node_Group,
        Node_Legacy,
        Node_SubgraphNode,
        Node_AssetInstance,     //the asset node which generated by main graph tree.
        Node_AssetReference,    //the asset node which created in another asset graph.
        NoVersionNode
    };

    enum SUBGRAPH_TYPE
    {
        SUBGRAPH_NOR = 0,
        SUBGRAPH_METERIAL,
        SUBGRAPH_PRESET
    };

    enum SubnetType
    {
        Subnet_Normal,
        Subnet_Material,
        Subnet_Main,    //only one main graph on whole zeno system.
    };

    enum SocketProperty : unsigned int
    {
        Socket_Normal,
        Socket_Editable,
        Socket_MultiInput,
        Socket_Legacy,
    };
    ENUM_FLAGS(SocketProperty)

    enum SocketType
    {
        NoSocket,
        //Socket_Primitve,
        //zeno::Socket_ReadOnly,
        Socket_Output,      //Output object

        //obj:
        Socket_ReadOnly,
        Socket_Clone,
        Socket_Owning,
        //primitive
        Socket_Primitve,

        Socket_WildCard
    };

    enum NodeDataGroup
    {
        Role_InputObject,
        Role_InputPrimitive,
        Role_OutputObject,
        Role_OutputPrimitive
    };

    //ui issues:
    enum VParamType
    {
        Param_Root,
        Param_Tab,
        Param_Group,
        Param_Param
    };

    enum ParamControl
    {
        NullControl,
        Lineedit,
        Multiline,
        ReadPathEdit,
        WritePathEdit,
        DirectoryPathEdit,
        Combobox,
        Checkbox,
        Vec2edit,
        Vec3edit,
        Vec4edit,
        ColorVec,
        Heatmap,
        CurveEditor,
        SpinBox,
        Slider,
        DoubleSpinBox,
        SpinBoxSlider,
        PythonEditor,
        PushButton,
        Seperator,
        CodeEditor,
        NoMultiSockPanel,   //disable dist/list panel
    };

    enum LinkFunction
    {
        Link_Copy,
        Link_Ref
    };

    enum NodeRunStatus
    {
        Node_DirtyReadyToRun,       //已标脏，但还没执行计算。  （dirty)
        Node_Pending,               //已进入计算，但还须等待前序计算依赖。(dirty)
        Node_Running,               //进入apply   (dirty)
        Node_RunError,              //计算错误      (dirty)
        Node_RunSucceed             //计算成功并完成   (no dirty)
    };

    enum ZSG_VERSION
    {
        VER_2,          //old version io
        VER_2_5,        //new version io
        VER_3,          //the final io format, supporting tree layout.
        UNKNOWN_VER,
    };

    using zvariant = std::variant<
        int, zeno::vec2i, zeno::vec3i, zeno::vec4i,
        float, zeno::vec2f, zeno::vec3f, zeno::vec4f,
        zeno::vec2s, zeno::vec3s, zeno::vec4s, std::string>;

    using AttrValue = std::variant<float, int, vec3f, vec2f, vec4f, std::string>;

    using ctrlpropvalue = std::variant<
        std::vector<std::string>,
        int,
        float,
        std::string>;

    using ObjPath = std::string;

    typedef std::function<void(ObjPath, bool, NodeRunStatus)> F_NodeStatus;
}


#endif